### ISSUE TITLE
Finish first deliverables checklist.

### ISSUE THREAD

**Issue by RhadMax** [rschle/dani#5]
- [X ] -  Wireframe images
- [x] - Overview of app and the WHY 
- [x] - Breakdown of Roles by group member
- [x] - Schedule for completion of tasks
- [x] - Screenshot of project board from github
